# Generated by Django 5.0.1 on 2024-01-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainservice',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subservice',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
