# Generated by Django 5.0.1 on 2024-01-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_mainservice_is_active_subservice_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
