# Generated by Django 5.0.1 on 2024-01-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_mainservice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
