# Generated by Django 5.0.1 on 2024-01-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_subservice_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subservice',
            old_name='name',
            new_name='sub_name',
        ),
    ]
