# Generated by Django 5.0.1 on 2024-01-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_rename_name_subservice_sub_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subservice',
            old_name='sub_name',
            new_name='name',
        ),
    ]
