# Generated by Django 5.0.1 on 2024-01-17 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_subservice_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='mainservice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subservice', to='service.mainservice'),
        ),
    ]
