# Generated by Django 5.0.1 on 2024-01-09 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePostion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postion_name', models.CharField(blank=True, max_length=50, null=True)),
                ('postion_titile', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-binary'), ('P', 'Prefer not to say')], max_length=1)),
                ('phone_number', models.BigIntegerField(max_length=10, unique=True)),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('address', models.TextField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('type_of_work', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CT', 'Contract'), ('IT', 'Internship')], default='FT', max_length=2)),
                ('adhar_number', models.BigIntegerField(unique=True)),
                ('images', models.ImageField(upload_to='Image')),
                ('is_active', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=50)),
                ('bank_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_auth.bankdetails')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_auth.employeepostion')),
            ],
        ),
    ]
