# Generated by Django 5.0.1 on 2024-01-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_auth', '0005_remove_employeepostion_postion_titile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeepostion',
            old_name='postion_name',
            new_name='name',
        ),
    ]
