# Generated by Django 5.0.1 on 2024-01-11 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employee_auth', '0007_employees_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='groups',
            field=models.ManyToManyField(related_name='employees_groups', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='employees',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='employees',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='employees',
            name='user_permissions',
            field=models.ManyToManyField(related_name='employees_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone_number',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits only.', regex='^\\d{10}')]),
        ),
        migrations.RemoveField(
            model_name='employees',
            name='position',
        ),
        migrations.AddField(
            model_name='employees',
            name='position',
            field=models.ManyToManyField(to='employee_auth.employeepostion'),
        ),
    ]
