# Generated by Django 5.0.1 on 2024-01-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_auth', '0008_employees_groups_employees_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
