# Generated by Django 5.0.1 on 2024-01-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_auth', '0009_alter_employees_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='images',
            field=models.ImageField(blank=True, upload_to='Image'),
        ),
    ]
