# Generated by Django 5.0.1 on 2024-01-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_auth', '0011_employees_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='max_otp_try',
            field=models.CharField(default=3, max_length=2),
        ),
        migrations.AddField(
            model_name='employees',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='otp_time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
