# Generated by Django 5.0.1 on 2024-01-12 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_auth', '0014_remove_employees_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='address',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='adhar_number',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-binary'), ('P', 'Prefer not to say')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='max_otp_try',
            field=models.CharField(default=3, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone_number',
            field=models.BigIntegerField(null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits only.', regex='^\\d{10}')]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.ManyToManyField(null=True, to='employee_auth.employeepostion'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='type_of_work',
            field=models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CT', 'Contract'), ('IT', 'Internship')], default='FT', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
