# Generated by Django 5.0.1 on 2024-01-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_auth', '0015_alter_employees_address_alter_employees_adhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.ManyToManyField(blank=True, to='employee_auth.employeepostion'),
        ),
    ]
