# Generated by Django 5.0.1 on 2024-01-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_auth', '0017_parent_child'),
    ]

    operations = [
        migrations.DeleteModel(
            name='child',
        ),
        migrations.DeleteModel(
            name='parent',
        ),
    ]
