# Generated by Django 5.0.1 on 2024-01-13 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_auth', '0018_delete_child_delete_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='location',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='max_otp_try',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='otp_expiry',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='otp_time_out',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='employees',
            name='role',
            field=models.IntegerField(choices=[(1, 'ADMIN'), (2, 'EMPLOYEE'), (3, 'USER')], default=2),
        ),
        migrations.AddField(
            model_name='employees',
            name='usermodel_ptr',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
