# Generated by Django 5.0.1 on 2024-01-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_auth', '0021_remove_employees_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='role',
            field=models.IntegerField(choices=[(1, 'ADMIN'), (2, 'EMPLOYEE'), (3, 'USER')], default=2),
        ),
    ]
