# Generated by Django 5.0.1 on 2024-01-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_auth', '0022_employees_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='role',
        ),
    ]
