# Generated by Django 5.0.1 on 2024-01-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_auth', '0023_remove_employees_role'),
        ('service', '0009_alter_subservice_mainservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='position',
        ),
        migrations.AddField(
            model_name='employees',
            name='service',
            field=models.ManyToManyField(blank=True, to='service.subservice'),
        ),
    ]
