# Generated by Django 5.0.1 on 2024-01-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_auth', '0024_remove_employees_position_employees_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
