# Generated by Django 5.0.1 on 2024-01-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_auth', '0025_employees_latitude_employees_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='images',
        ),
    ]
