# Generated by Django 5.0.1 on 2024-02-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_likes_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='employee',
            new_name='user',
        ),
    ]
