# Generated by Django 4.2.10 on 2024-02-14 06:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_auth', '0026_remove_employees_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0003_alter_reviews_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='EmployeeReviews',
        ),
    ]
