# Generated by Django 5.0.1 on 2024-02-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='thread_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
