# Generated by Django 5.0.1 on 2024-01-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerservice',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
