# Generated by Django 5.0.1 on 2024-02-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_employeeaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaction',
            name='action',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
    ]
