# Generated by Django 5.0.1 on 2024-02-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_appointment_paid_at_appointment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('ST', 'Stripe'), ('CO', 'Cash on Delivery'), ('PD', 'Pending')], default='PD', max_length=2, null=True),
        ),
    ]
