# Generated by Django 5.0.1 on 2024-02-11 16:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_appointment_user'),
        ('payment', '0002_serviceorder_delete_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceOrder',
            new_name='ServiceOrderPayment',
        ),
    ]
