# Generated by Django 4.2.3 on 2024-01-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
