# Generated by Django 4.2.3 on 2024-01-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_customer_otp_customer_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='max_otp_try',
            field=models.CharField(default=3, max_length=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='otp_max_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
