# Generated by Django 4.2.3 on 2024-01-08 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_customer_max_otp_try_customer_otp_max_out'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
