# Generated by Django 5.0.1 on 2024-01-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_usermodel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
