# Generated by Django 5.0.1 on 2024-01-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_usermodel_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='role',
        ),
    ]
