# Generated by Django 5.0.1 on 2024-01-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_remove_usermodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.IntegerField(choices=[(1, 'ADMIN'), (2, 'EMPLOYEE'), (3, 'USER')], null=True),
        ),
    ]
