# Generated by Django 5.0.1 on 2024-01-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_usermodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='max_otp_try',
            field=models.CharField(default=4, max_length=2),
        ),
    ]
