# Generated by Django 5.0.1 on 2024-01-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0012_alter_usermodel_max_otp_try'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
