# Generated by Django 5.0.1 on 2024-01-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_alter_usermodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='Images'),
        ),
    ]
