# Generated by Django 5.0.1 on 2024-01-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Banner_image')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Banner_image')),
                ('description', models.TextField()),
            ],
        ),
    ]
