# Generated by Django 5.0.1 on 2024-01-31 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebanner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userbanner',
            name='description',
        ),
    ]
